export const ROLES = {
  PFLEGEKRAFT: 'pflegekraft',
  TEAMLEITUNG: 'teamleitung',
  ADMIN: 'admin'
};

export const PERMISSIONS = {
  PATIENT_READ: 'patient:read',
  PATIENT_CREATE: 'patient:create'
};

export const ROLE_PERMISSIONS = {
  [ROLES.PFLEGEKRAFT]: [PERMISSIONS.PATIENT_READ],
  [ROLES.TEAMLEITUNG]: [PERMISSIONS.PATIENT_READ, PERMISSIONS.PATIENT_CREATE],
  [ROLES.ADMIN]: [PERMISSIONS.PATIENT_READ, PERMISSIONS.PATIENT_CREATE]
};
